### ISSUE TITLE
DataSource Switch中HikariCP无法设置maximum-pool-size

### ISSUE THREAD

**Issue by hengboy** [minbox-projects/minbox-datasource-switch#1]
来源：[https://gitee.com/minbox-projects/api-boot/issues/I1PBHC](https://gitee.com/minbox-projects/api-boot/issues/I1PBHC)
```
hikari:
        lzj:
          url: .......
          username: ....
          password: .........
          driver-class-name: oracle.jdbc.OracleDriver
          property:
            maximum-pool-size: 5
```
设置后还是默认的10个...
